### ISSUE TITLE
IBP 2.0 Build A Network Docs requires an 'affiliation' field

### ISSUE THREAD

**Issue by danny-ibm** [IBM-Bluemix-Docs/blockchain#138] opened 2019-02-28 19:00 UTC
Step 4 https://cloud.ibm.com/docs/services/blockchain/howto?topic=blockchain-ibp-console-build-network#ibp-console-build-network-use-CA-org1 
The affiliation field is for advanced users and is not used by the tutorial.

There's no dropdown, it's a mandatory text field. (will not let you continue)

![image](https://user-images.githubusercontent.com/42442504/53591056-26c7b700-3b61-11e9-9637-e38f303e97b4.png)

**Comment by wjzhengsh** [comment] 2019-03-06 03:36
Thanks for opening the issue, @danny-ibm !

We are aware of the problem and we'll keep you updated on the fix.

**Comment by pamandrejko** [comment] 2019-03-20 19:54
@danny-ibm  Again, thank for you this feedback.

We have updated every place in our documentation where we mention this affiliation field and we now indicate that it is required field. For example, see step 4 in this content:
https://cloud.ibm.com/docs/services/blockchain/howto?topic=blockchain-ibp-console-build-network#ibp-console-build-network-use-CA-org1

The affiliation list drop-down should never be empty and development has been working on addressing that issue.

**Comment by danny-ibm** [comment] 2019-03-20 20:12
NP Pam! Thanks for addressing the issue :)

**Comment by wjzhengsh** [comment] 2019-03-22 03:11
I'm closing this issue. 

@danny-ibm If you have other feedback, welcome to open new issues.

**Comment by danny-ibm** [comment] 2019-03-22 05:56
@wjzhengsh I don't think this issue should be closed as the platform is still showing a mandatory **textbox** and not a **dropdown** as documented. See below: 

![image](https://user-images.githubusercontent.com/42442504/54803391-b84cb500-4c45-11e9-99c6-a22b77b5aeda.png)

**Comment by wjzhengsh** [comment] 2019-03-22 07:16
@danny-ibm Let's reopen it for now.  But could you try with a new service instance?  We have a code refresh this week.

**Comment by pamandrejko** [comment] 2019-03-22 12:24
Checking with development on this one

**Comment by pamandrejko** [comment] 2019-03-22 13:19
@danny-ibm Development has confirmed that you need to get a new Service Instance to see the fix.

We can leave this open until you confirm that works for you.

**Comment by wjzhengsh** [comment] 2019-04-24 02:02
@danny-ibm How are you? Have you had a chance to provision new service instance to test out the latest version of the IBM Blockchain Platform console? We hope the problem is fixed.

**Comment by pamandrejko** [comment] 2019-06-07 19:21
Closing as the flow as now changed and the doc has been updated.

**Closed by pamandrejko** 2019-06-07 19:21 UTC
